export type ProjectDetail = {
  slug: string;
  title: string;
  category: string;
  location: string;
  year: string;
  area: string;
  scope: string;
  intro: string;
  images: string[];
};

const C = "/eurowindow/constructions/";
const H = "/eurowindow/";

export const projects: ProjectDetail[] = [
  {
    slug: "cang-hang-khong-phu-bai-hue",
    title: "Cảng hàng không Phú Bài Huế",
    category: "Công trình quốc gia",
    location: "Huế",
    year: "2023",
    area: "Nhà ga T2",
    scope: "Cửa & vách nhôm kính",
    intro: "Eurowindow cung cấp và lắp đặt hệ cửa, vách nhôm kính cho nhà ga T2 Cảng hàng không quốc tế Phú Bài — đáp ứng tiêu chuẩn an toàn, cách âm cho công trình giao thông trọng điểm.",
    images: [C + "viber-image-2025-02-05-13-33-24-065.png.webp", H + "untitled-1-01.jpg.webp", H + "banner-02-1.png.webp"],
  },
  {
    slug: "benh-vien-viet-phap",
    title: "Bệnh viện Việt Pháp",
    category: "Bệnh viện",
    location: "Hà Nội",
    year: "2024",
    area: "Bệnh viện quốc tế",
    scope: "Cửa & vách nhôm kính",
    intro: "Hệ cửa và vách kính cách âm, cách nhiệt cho Bệnh viện Việt Pháp — đảm bảo không gian y tế tiện nghi, sạch khuẩn và tối ưu ánh sáng tự nhiên.",
    images: [C + "img-7105.jpg.webp", C + "dji-0090-1.jpg.webp", C + "img-7172.jpg.webp"],
  },
  {
    slug: "benh-vien-ung-buou-da-nang",
    title: "Bệnh viện ung bướu Đà Nẵng",
    category: "Bệnh viện",
    location: "Đà Nẵng",
    year: "2023",
    area: "Bệnh viện chuyên khoa",
    scope: "Cửa & vách nhôm kính",
    intro: "Cung cấp hệ cửa uPVC và vách nhôm kính cho Bệnh viện ung bướu Đà Nẵng — một trong những công trình y tế trọng điểm khu vực miền Trung.",
    images: [C + "benh-vien-ung-buou-da-nang-17.jpg.webp", C + "dji-0090-1.jpg.webp", C + "img-7105.jpg.webp"],
  },
  {
    slug: "benh-vien-nhi-dong-tphcm",
    title: "Bệnh viện Nhi đồng TP. Hồ Chí Minh",
    category: "Bệnh viện",
    location: "TP. Hồ Chí Minh",
    year: "2023",
    area: "Bệnh viện nhi khoa",
    scope: "Cửa & vách nhôm kính",
    intro: "Hệ cửa và vách kính an toàn, cách âm cho khu khám chữa bệnh Bệnh viện Nhi đồng TP. Hồ Chí Minh.",
    images: [C + "dji-0090-1.jpg.webp", C + "img-7172.jpg.webp", C + "benh-vien-ung-buou-da-nang-17.jpg.webp"],
  },
  {
    slug: "trung-tam-truyen-hinh-ttxvn",
    title: "TT Truyền hình Thông tấn xã Việt Nam",
    category: "Trụ sở cơ quan",
    location: "Hà Nội",
    year: "2022",
    area: "Trụ sở truyền hình",
    scope: "Cửa & vách nhôm kính",
    intro: "Cung cấp hệ vách nhôm kính lớn và cửa cách âm cho Trung tâm Truyền hình Thông tấn xã Việt Nam — công trình báo chí hiện đại.",
    images: [C + "img-7172.jpg.webp", C + "20191115-vien-kiem-soat-nhan-dan-toi-cao-0038.jpg.webp", C + "img-7105.jpg.webp"],
  },
  {
    slug: "vien-kiem-sat-nhan-dan-toi-cao",
    title: "Trụ sở Viện KSND Tối cao",
    category: "Trụ sở cơ quan",
    location: "Hà Nội",
    year: "2021",
    area: "Trụ sở tối cao",
    scope: "Cửa & vách nhôm kính",
    intro: "Hệ cửa và vách kính tiêu chuẩn cho Trụ sở Viện Kiểm sát nhân dân tối cao — công trình trọng điểm của ngành kiểm sát.",
    images: [C + "20191115-vien-kiem-soat-nhan-dan-toi-cao-0038.jpg.webp", C + "img-7172.jpg.webp", C + "viber-image-2025-02-05-13-33-24-065.png.webp"],
  },
  {
    slug: "toa-nha-quoc-hoi",
    title: "Tòa nhà Quốc hội",
    category: "Công trình quốc gia",
    location: "Hà Nội",
    year: "2019",
    area: "Nhà Quốc hội",
    scope: "Cửa & vách nhôm kính",
    intro: "Sản phẩm Eurowindow hiện diện tại Nhà Quốc hội — biểu tượng của sự tự hào dân tộc, minh chứng cho chất lượng đạt chuẩn công trình quốc gia.",
    images: [C + "mg-1220.jpg.webp", H + "banner-02-1.png.webp", C + "20191115-vien-kiem-soat-nhan-dan-toi-cao-0038.jpg.webp"],
  },
  {
    slug: "trung-tam-thuong-mai",
    title: "Trung tâm thương mại & văn phòng",
    category: "Văn phòng",
    location: "Hà Nội",
    year: "2023",
    area: "Tòa nhà văn phòng",
    scope: "Cửa & vách nhôm kính",
    intro: "Mặt tiền kính lớn, cửa tự động và hệ vách ngăn thông minh cho không gian thương mại, văn phòng hiện đại.",
    images: [C + "20190612-hanoi-cityscape-7928.jpg.webp", H + "cua-tu-dong.jpg.webp", H + "banner-02-1.png.webp"],
  },
  {
    slug: "chung-cu-vinhomes-global-gate",
    title: "Khu đô thị Vinhomes Global Gate Cổ Loa",
    category: "Văn phòng",
    location: "Hà Nội",
    year: "2024",
    area: "Khu đô thị",
    scope: "Cửa & vách nhôm kính",
    intro: "Eurowindow cung cấp và lắp đặt cửa, vách kính cho khu đô thị Vinhomes Global Gate Cổ Loa.",
    images: [H + "img-0344.jpeg.webp", H + "ewh07548-large.jpg.webp", H + "cua-nhom-kinh-cach-am-1.jpg.webp"],
  },
  {
    slug: "toa-nha-van-phong-chinh-phu",
    title: "Tòa nhà văn phòng Chính phủ",
    category: "Công trình quốc gia",
    location: "Hà Nội",
    year: "2022",
    area: "Tòa nhà Chính phủ",
    scope: "Cửa sổ, vách nhôm kính, cửa gỗ, mái kính Skylight, cửa thép chống cháy",
    intro: "Công trình Tòa nhà văn phòng Chính phủ có ý nghĩa quan trọng, biểu tượng cho cơ quan cao nhất của Chính phủ trong giai đoạn phát triển đổi mới. Eurowindow thi công các hạng mục: cửa sổ và vách nhôm kính lớn mặt dựng, cửa gỗ, mái kính Skylight và lam nhôm trên mái, cửa thép chống cháy, cửa nhôm chống cháy và vách kính hoa văn.",
    images: [C + "20190612-hanoi-cityscape-7928.jpg.webp", C + "20190920-van-phong-chinh-phu-dsc6708-hdr.jpg.webp", C + "20190920-van-phong-chinh-phu-dsc6692-hdr.jpg.webp"],
  },
  {
    slug: "tru-so-bo-cong-an",
    title: "Trụ sở Bộ Công an",
    category: "Công trình quốc gia",
    location: "Hà Nội",
    year: "2021",
    area: "Toà nhà Bộ Công an",
    scope: "Mặt dựng hệ nhôm kính, ốp nhôm mặt đứng",
    intro: "Công trình trụ sở Bộ Công an được xây dựng trên diện tích 5,3ha, quy mô 182.000 m2 sàn với 6 khối nhà C, D, E, B1, B3 và B5. Eurowindow phụ trách thi công lắp đặt mặt dựng hệ nhôm kính và ốp nhôm mặt đứng của các khối nhà.",
    images: [C + "toa-nha-bo-cong-an-large.jpg", C + "50522321.jpg.webp", C + "b-u1ed9-cong-an.jpg.webp"],
  },
  {
    slug: "tru-so-bo-ngoai-giao",
    title: "Trụ sở Bộ Ngoại giao",
    category: "Công trình quốc gia",
    location: "Hà Nội",
    year: "2022",
    area: "Tòa nhà Bộ Ngoại giao",
    scope: "Cửa nhôm kính, cửa chống cháy",
    intro: "Trụ sở Bộ Ngoại giao là 1 trong 6 công trình \"Kiến trúc Pháp trong lòng Hà Nội\" với tổng mức đầu tư khoảng 3.500 tỷ đồng. Eurowindow thi công lắp đặt hơn 8.000 m2 cửa nhôm và vách nhôm kính lớn, cửa chống cháy.",
    images: [C + "20191030-tru-so-bo-ngoai-giao-0719-large.jpg", C + "img-0133.jpg.webp", C + "1467270859-3.jpg.webp"],
  },
  {
    slug: "cang-hang-khong-quoc-te-can-tho",
    title: "Cảng hàng không quốc tế Cần Thơ",
    category: "Công trình quốc gia",
    location: "Cần Thơ",
    year: "2021",
    area: "Nhà ga hành khách",
    scope: "Vách nhôm kính lớn, cửa chống khói thông minh",
    intro: "Cảng hàng không quốc tế Cần Thơ với tổng vốn đầu tư khoảng 150 triệu USD. Eurowindow thi công vách kính Spider với hệ thống khung thép đỡ, cáp giằng Inox 316 và hệ thống cửa chống khói thông minh tự động.",
    images: [C + "san-bay-can-tho-large.jpg", C + "san-bay-can-tho-3.png.webp"],
  },
  {
    slug: "khu-doi-thi-sala",
    title: "Khu đô thị Sala",
    category: "Công trình dân dụng",
    location: "Hà Nội",
    year: "2022",
    area: "Khu đô thị",
    scope: "Cửa & vách nhôm kính",
    intro: "Dự án căn hộ dịch vụ cao cấp Khu đô thị Sala tại quận 2, TP. HCM. Eurowindow cung cấp và lắp đặt hệ cửa nhôm kính và vách nhôm kính cho các tòa nhà chung cư cao tầng.",
    images: [C + "dji-0155-large.jpg", C + "dji-0153-1.jpg.webp"],
  },
  {
    slug: "du-an-khai-son-hill",
    title: "Dự án Khai Sơn Hill",
    category: "Công trình dân dụng",
    location: "Hà Nội",
    year: "2022",
    area: "Biệt thự thung lũng",
    scope: "Cửa & vách nhôm kính",
    intro: "Dự án biệt thự Khai Sơn Hill với kiến trúc hiện đại kết hợp thiên nhiên. Eurowindow thi công hệ cửa nhôm kính, vách kính lớn và cửa ban công cho các biệt thự.",
    images: [C + "dji-0470-hdr-large.jpg", C + "dji-0485-hdr.jpg.webp", C + "dji-0482-hdr.jpg.webp"],
  },
  {
    slug: "nha-pho-chua-thong-son-tay",
    title: "Nhà phố Chùa Thông, TX. Sơn Tây",
    category: "Công trình dân dụng",
    location: "Sơn Tây, Hà Nội",
    year: "2022",
    area: "Nhà phố thương mại",
    scope: "Cửa sổ nhôm EA55, cửa đi EA90, vách nhôm kính FA52",
    intro: "Căn nhà phố rộng 400m2, 6 tầng tại đườờng Chùa Thông, TX. Sơn Tây. Gia chủ sử dụng cửa sổ, cửa đi mở quay, cửa xếp trượt hệ nhôm EA55/EA90 và vách dựng mặt tiền FA52.",
    images: [C + "1-2-large.jpg", C + "10-1.jpg.webp", C + "4-2.jpg.webp"],
  },
  {
    slug: "biet-thu-phu-thinh-son-tay",
    title: "Biệt thự KĐT Phú Thịnh, Sơn Tây",
    category: "Công trình dân dụng",
    location: "Sơn Tây, Hà Nội",
    year: "2022",
    area: "Biệt thự 3 tầng",
    scope: "Cửa & vách nhôm kính Cmech",
    intro: "Biệt thự 3 tầng phong cách Tân cổ điển tại KĐT Phú Thịnh, Sơn Tây. Cửa đi, cửa sổ và vách nhôm kính Eurowindow với phụ kiện Cmech (Hoa Kỳ) sơn màu vàng đồng.",
    images: [C + "1-1-large.jpg", C + "3-1.jpg.webp", C + "5-2.jpg.webp"],
  },
  {
    slug: "biet-thu-green-pearl-minh-khai",
    title: "Biệt thự KĐT Green Pearl 378 Minh Khai",
    category: "Công trình dân dụng",
    location: "Hà Nội",
    year: "2022",
    area: "Biệt thự caọ nguyên",
    scope: "Cửa & vách nhôm kính EA55, kính hộp 2 lớp",
    intro: "Biệt thự hiện đại tại KĐT Green Pearl, Hà Nội. Eurowindow lắp đặt cửa nhôm EA55 sơn vân gỗ, kính hộp 2 lớp cường lực với phụ kiện Roto (Đức).",
    images: [C + "1-large.jpg", C + "fkr0171-copy.jpg.webp", C + "2.jpg.webp"],
  },
];

export function getProject(slug: string) {
  return projects.find((p) => p.slug === slug);
}
