export type ProjectDetail = {
  slug: string;
  title: string;
  category: string;
  location: string;
  year: string;
  area: string;
  scope: string;
  intro: string;
  images: string[];
};

const C = "/eurowindow/constructions/";
const H = "/eurowindow/";

export const projects: ProjectDetail[] = [
  {
    slug: "cang-hang-khong-phu-bai-hue",
    title: "Phu Bai International Airport",
    category: "National landmark",
    location: "Hue",
    year: "2023",
    area: "Terminal T2",
    scope: "Doors & glass partitions",
    intro: "Eurowindow supplied and installed aluminium door and glass partition systems for Terminal T2 of Phu Bai International Airport — meeting safety and acoustic standards for a key transport project.",
    images: [C + "viber-image-2025-02-05-13-33-24-065.png.webp"],
  },
  {
    slug: "benh-vien-viet-phap",
    title: "Hospital Francais de Hanoi",
    category: "Hospital",
    location: "Hanoi",
    year: "2024",
    area: "International hospital",
    scope: "Doors & glass partitions",
    intro: "Acoustic and thermal door and glass partition systems for Hospital Francais de Hanoi — ensuring a comfortable, hygienic medical space with optimised natural light.",
    images: [C + "img-7105.jpg.webp", C + "img-7096.jpg.webp", C + "img-7125.jpg.webp", C + "img-7112.jpg.webp"],
  },
  {
    slug: "benh-vien-ung-buou-da-nang",
    title: "Da Nang Oncology Hospital",
    category: "Hospital",
    location: "Da Nang",
    year: "2023",
    area: "Specialist hospital",
    scope: "Doors & glass partitions",
    intro: "uPVC door and aluminium glass partition systems for Da Nang Oncology Hospital — a key healthcare project in central Vietnam.",
    images: [C + "benh-vien-ung-buou-da-nang-17.jpg.webp", C + "bv-1598244674808.jpg.webp", C + "96826194.jpg.webp"],
  },
  {
    slug: "benh-vien-nhi-dong-tphcm",
    title: "Children's Hospital 2 Ho Chi Minh City",
    category: "Hospital",
    location: "Ho Chi Minh City",
    year: "2023",
    area: "Paediatric hospital",
    scope: "Doors & glass partitions",
    intro: "Safe, acoustic door and glass partition systems for the clinical block of Children's Hospital 2 Ho Chi Minh City.",
    images: [C + "dji-0090-1.jpg.webp", C + "dji-0074.jpg.webp", C + "dji-0072.jpg.webp", C + "dji-0086.jpg.webp"],
  },
  {
    slug: "trung-tam-truyen-hinh-ttxvn",
    title: "Vietnam News Agency TV Centre",
    category: "Government building",
    location: "Hanoi",
    year: "2022",
    area: "Broadcasting centre",
    scope: "Doors & glass partitions",
    intro: "Large aluminium glass partition and acoustic door systems for the Vietnam News Agency TV Centre — a modern media landmark.",
    images: [C + "img-7172.jpg.webp", C + "img-7176.jpg.webp", C + "img-7189.jpg.webp"],
  },
  {
    slug: "vien-kiem-sat-nhan-dan-toi-cao",
    title: "Supreme People's Procuracy",
    category: "Government building",
    location: "Hanoi",
    year: "2021",
    area: "Supreme agency",
    scope: "Doors & glass partitions",
    intro: "Standard door and glass partition systems for the Supreme People's Procuracy building — a landmark of the prosecutorial sector.",
    images: [C + "20191115-vien-kiem-soat-nhan-dan-toi-cao-0038.jpg.webp", C + "20191115-vien-kiem-soat-nhan-dan-toi-cao-0027.jpg.webp"],
  },
  {
    slug: "toa-nha-quoc-hoi",
    title: "National Assembly Building",
    category: "National landmark",
    location: "Hanoi",
    year: "2019",
    area: "National Assembly",
    scope: "Doors & glass partitions",
    intro: "Eurowindow products appear in the National Assembly Building — a symbol of national pride and proof of quality meeting national landmark standards.",
    images: [C + "mg-1220.jpg.webp", C + "dsc5755.jpg.webp", C + "dsc5767.jpg.webp", C + "dsc5733.jpg.webp", C + "img-3596.jpg.webp"],
  },
  {
    slug: "toa-nha-van-phong-chinh-phu",
    title: "Government Office Building",
    category: "National landmark",
    location: "Hanoi",
    year: "2022",
    area: "Government Office Building",
    scope: "Aluminium doors & glass partitions, timber doors, skylights, fire-rated steel doors",
    intro: "The Government Office Building is a significant project and symbol of the government's highest office. Eurowindow executed aluminium window and large glass partition systems, timber doors, skylights, fire-rated steel/aluminium doors and decorative glass partitions.",
    images: [C + "20190612-hanoi-cityscape-7928.jpg.webp", C + "20190920-van-phong-chinh-phu-dsc6708-hdr.jpg.webp", C + "20190920-van-phong-chinh-phu-dsc6692-hdr.jpg.webp"],
  },
  {
    slug: "tru-so-bo-cong-an",
    title: "Public Security Ministry Headquarters",
    category: "National landmark",
    location: "Hanoi",
    year: "2021",
    area: "Public Security Ministry",
    scope: "Aluminium curtain wall & cladding",
    intro: "The Public Security Ministry Headquarters spans 5.3 hectares with 182,000 m² floor area across blocks C, D, E, B1, B3 and B5. Eurowindow executed the aluminium curtain wall and aluminium cladding systems for the project.",
    images: [C + "toa-nha-bo-cong-an-large.jpg", C + "50522321.jpg.webp", C + "b-u1ed9-cong-an.jpg.webp"],
  },
  {
    slug: "tru-so-bo-ngoai-giao",
    title: "Ministry of Foreign Affairs Headquarters",
    category: "National landmark",
    location: "Hanoi",
    year: "2022",
    area: "Ministry of Foreign Affairs",
    scope: "Aluminium doors & fire-rated glass partitions",
    intro: "The Ministry of Foreign Affairs Headquarters is one of six \"French Architecture in Hanoi\" projects with an investment of approximately VND 3,500 billion. Eurowindow supplied and installed over 8,000 m² of aluminium doors and large glass partitions, plus fire-rated doors.",
    images: [C + "20191030-tru-so-bo-ngoai-giao-0719-large.jpg", C + "img-0133.jpg.webp", C + "1467270859-3.jpg.webp"],
  },
  {
    slug: "cang-hang-khong-quoc-te-can-tho",
    title: "Can Tho International Airport",
    category: "National landmark",
    location: "Can Tho",
    year: "2021",
    area: "Passenger Terminal",
    scope: "Large glass partitions & intelligent smoke-free doors",
    intro: "Can Tho International Airport with an investment of approximately 150 million USD. Eurowindow executed Spider glass wall systems with steel frame, Inox 316 and CF8M tension cables, plus intelligent smoke-free door systems.",
    images: [C + "san-bay-can-tho-large.jpg", C + "san-bay-can-tho-3.png.webp"],
  },
  {
    slug: "khu-doi-thi-sala",
    title: "Sala Urban Area",
    category: "Residential",
    location: "Ho Chi Minh City",
    year: "2022",
    area: "Urban area",
    scope: "Aluminium doors & glass partitions",
    intro: "Sala Urban Area — high-end serviced apartment complex in District 2, Ho Chi Minh City. Eurowindow supplied and installed aluminium and glass partition systems for the high-rise residential towers.",
    images: [C + "dji-0155-large.jpg", C + "dji-0153-1.jpg.webp"],
  },
  {
    slug: "du-an-khai-son-hill",
    title: "Khai Son Hill Residential Project",
    category: "Residential",
    location: "Hanoi",
    year: "2022",
    area: "Hillside villas",
    scope: "Aluminium doors & glass partitions",
    intro: "Khai Sơn Hill residential project featuring modern architecture blended with natural landscape. Eurowindow installed aluminium sliding door systems, large glass partitions and balcony doors for the villas.",
    images: [C + "dji-0470-hdr-large.jpg", C + "dji-0485-hdr.jpg.webp", C + "dji-0482-hdr.jpg.webp"],
  },
  {
    slug: "nha-pho-chua-thong-son-tay",
    title: "Chua Thong Townhouse, Son Tay",
    category: "Residential",
    location: "Son Tay, Hanoi",
    year: "2022",
    area: "Commercial townhouse",
    scope: "Aluminium windows (EA55), sliding doors (EA90), front glass walls (FA52)",
    intro: "A 400 m², 6-storey commercial townhouse on Chua Thong Street, Son Tay. The owner installed Eurowindow aluminium windows, outward-opening and sliding doors (EA55/EA90 profiles) plus aluminium glass front walls (FA52).",
    images: [C + "1-2-large.jpg", C + "10-1.jpg.webp", C + "4-2.jpg.webp"],
  },
  {
    slug: "biet-thu-fu-thi-son-tay",
    title: "Fu Thin Villa, Son Tay Urban Area",
    category: "Residential",
    location: "Son Tay, Hanoi",
    year: "2022",
    area: "3-storey villa",
    scope: "Aluminium doors & glass partitions (Cmech hardware)",
    intro: "A 3-storey neo-classical villa at Phu Thinh Urban Area, Son Tay. Eurowindow aluminium doors, windows and glass partitions with authentic Cmech (USA) hardware in bronze finish.",
    images: [C + "1-1-large.jpg", C + "3-1.jpg.webp", C + "5-2.jpg.webp"],
  },
  {
    slug: "bie-thu-green-pearl-minh-khai",
    title: "Green Pearl Villa, Minh Khai Urban Area",
    category: "Residential",
    location: "Hanoi",
    year: "2022",
    area: "Hillside villa",
    scope: "Aluminium doors & double-glazed glass partitions (EA55, Roto hardware)",
    intro: "A modern villa at Green Pearl Urban Area, Hanoi featuring Eurowindow aluminium doors (EA55 with wood-grain finish) and double-glazed safety glass, fitted with Roto (Germany) hardware.",
    images: [C + "1-large.jpg", C + "fkr0171-copy.jpg.webp", C + "2.jpg.webp"],
  },
];

export function getProject(slug: string) {
  return projects.find((p) => p.slug === slug);
}
