import type { AuditReport, ReviewResult, EnterpriseConfig } from "../types";
import { writeFileSync, existsSync, mkdirSync } from "node:fs";
import { join } from "node:path";

export class ReportGenerator {
  private projectRoot: string;
  private config: EnterpriseConfig;

  constructor(projectRoot: string, config: EnterpriseConfig) {
    this.projectRoot = projectRoot;
    this.config = config;
  }

  generateFullReport(
    report: AuditReport,
    outputPath?: string,
  ): { markdown: string; html: string } {
    const md = this.generateMarkdown(report);
    const html = this.generateHtml(report);

    const outDir = outputPath ?? join(this.projectRoot, ".enterprise", "reports");
    if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });

    const mdPath = join(outDir, `review-report-${Date.now()}.md`);
    const htmlPath = join(outDir, `review-report-${Date.now()}.html`);
    if (this.config.generateHtmlReports) {
      writeFileSync(htmlPath, html, "utf-8");
    }
    writeFileSync(mdPath, md, "utf-8");

    return { markdown: md, html: html };
  }

  private generateMarkdown(r: AuditReport): string {
    const rr = r.reviewResult;
    const s = {
      overall: r.healthScore,
      health: r.healthScore,
      security: r.securityScore,
      performance: r.performanceScore,
      seo: r.seoScore,
      maintainability: r.maintainabilityScore,
      codeQuality: r.codeQualityScore,
      architecture: r.architectureScore,
    };
    const d = r.technicalDebt;
    const pr = r.priorityList.slice(0, 20);
    const pf = r.patchFiles ?? [];

    return `# Enterprise AI Code Review Report

**Project**: ${rr.project.name} v${rr.project.version}
**Framework**: ${rr.project.framework} ${rr.project.frameworkVersion}
**Generated**: ${new Date().toISOString()}
**Duration**: ${rr.durationMs}ms

---

## Scores (Health Check)

| Metric | Score | Status |
|--------|-------|--------|
| Health | ${s.health}/100 | ${scoreStatus(s.health)} |
| Security | ${s.security}/100 | ${scoreStatus(s.security)} |
| Performance | ${s.performance}/100 | ${scoreStatus(s.performance)} |
| SEO | ${s.seo}/100 | ${scoreStatus(s.seo)} |
| Maintainability | ${s.maintainability}/100 | ${scoreStatus(s.maintainability)} |
| Code Quality | ${s.codeQuality}/100 | ${scoreStatus(s.codeQuality)} |
| Architecture | ${s.architecture}/100 | ${scoreStatus(s.architecture)} |
| **Overall** | **${s.overall}/100** | **${scoreStatus(s.overall)}** |

---

## Technical Debt

- **Estimated Fix Time**: ${d.estimatedHours} hours
- **Complexity**: ${d.complexity}
- **Hotspots**: ${d.hotspots.slice(0, 5).join(", ") || "None"}

---

## Priority List

| # | Severity | Confidence | Category | File:Line | Description | Est. Time |
|---|----------|------------|----------|-----------|-------------|-----------|
${pr.map((p, i) => `| ${i+1} | ${p.severity.toUpperCase()} | ${(p.confidence*100).toFixed(0)}% | ${p.category} | ${p.file}:${p.line} | ${truncate(p.title, 60)} | ${p.estimatedMinutes}m |`).join("\n")}

---

## Findings Summary

| Severity | Count |
|----------|-------|
| Critical | ${rr.summary.bySeverity.critical} |
| High | ${rr.summary.bySeverity.high} |
| Medium | ${rr.summary.bySeverity.medium} |
| Low | ${rr.summary.bySeverity.low} |
| **Total** | **${rr.summary.total}** |

### By Category

| Category | Count |
|----------|-------|
${Object.entries(rr.summary.byCategory).sort(([,a],[,b]) => (b as number)-(a as number)).map(([cat, count]) => `| ${cat} | ${count} |`).join("\n")}

---

## Fix Plans

${r.fixPlans.length === 0 ? "No fixes applied." : r.fixPlans.map(fp => `
### Finding: ${fp.findingId}
- **Status**: ${fp.status}
- **Auto-fixable**: ${fp.autoFixable ? "Yes" : "No"}
- **Confidence**: ${(fp.confidence * 100).toFixed(0)}%
- **Patches**: ${fp.patches.length}
${fp.error ? `- **Note**: ${fp.error}` : ""}
${fp.verification ? `- **Verification**: ${verificationSummary(fp.verification)}` : ""}
`).join("")}

---

## Architecture Graph

${this.generateArchitectureSection(rr)}

---

## Patch Files

${pf.length === 0 ? "No patches generated." : pf.map(p => `
### ${p.file}
**Description**: ${p.description}
\`\`\`diff
- ${p.old}
+ ${p.new}
\`\`\`
`).join("")}

---

## Commit Message

\`\`\`
${r.commitMessage}
\`\`\`

---

## Pull Request Summary

${r.prSummary}

---

*Generated by Enterprise AI Code Review System*
`;
  }

  private generateHtml(r: AuditReport): string {
    const s = {
      overall: r.healthScore,
      health: r.healthScore,
      security: r.securityScore,
      performance: r.performanceScore,
      seo: r.seoScore,
      maintainability: r.maintainabilityScore,
      codeQuality: r.codeQualityScore,
      architecture: r.architectureScore,
    };
    const rr = r.reviewResult;

    return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Enterprise AI Code Review — ${rr.project.name}</title>
<style>
  :root { --bg: #0b1628; --card: #1c2b3a; --text: #e8eef3; --accent: #0066aa; --border: #2a3f5f; --critical: #e74c3c; --high: #e67e22; --medium: #f39c12; --low: #27ae60; --dim: #8a9bae; }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Fira Code', 'Consolas', monospace; background: var(--bg); color: var(--text); line-height: 1.6; }
  .container { max-width: 1200px; margin: 0 auto; padding: 2rem; }
  h1 { color: var(--accent); border-bottom: 2px solid var(--accent); padding-bottom: .5rem; margin-bottom: 2rem; }
  h2 { color: var(--text); margin: 2rem 0 1rem; padding-bottom: .3rem; border-bottom: 1px solid var(--border); }
  h3 { color: var(--accent); margin: 1rem 0 .5rem; }
  .scores { display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr)); gap: 1rem; margin: 2rem 0; }
  .score-card { background: var(--card); border: 1px solid var(--border); border-radius: 8px; padding: 1rem; text-align: center; }
  .score-value { font-size: 2rem; font-weight: bold; }
  .score-label { color: var(--dim); font-size: .85rem; text-transform: uppercase; }
  .critical { color: var(--critical); } .high { color: var(--high); } .medium { color: var(--medium); } .low { color: var(--low); }
  table { width: 100%; border-collapse: collapse; margin: 1rem 0; }
  th, td { padding: .5rem .75rem; text-align: left; border-bottom: 1px solid var(--border); }
  th { color: var(--accent); font-weight: 600; }
  tr:hover { background: var(--card); }
  .badge { display: inline-block; padding: .15rem .5rem; border-radius: 4px; font-size: .8rem; font-weight: 600; }
  .badge-critical { background: rgba(231,76,60,.2); color: var(--critical); }
  .badge-high { background: rgba(230,126,34,.2); color: var(--high); }
  .badge-medium { background: rgba(243,152,18,.2); color: var(--medium); }
  .badge-low { background: rgba(39,174,96,.2); color: var(--low); }
  .badge-pass { background: rgba(39,174,96,.2); color: var(--low); }
  .badge-fail { background: rgba(231,76,60,.2); color: var(--critical); }
  .code-block { background: #010a1a; border-radius: 6px; padding: 1rem; overflow-x: auto; margin: .5rem 0; font-size: .85rem; }
  .diff-add { color: #27ae60; } .diff-del { color: #e74c3c; }
  .pr-summary { background: var(--card); border-radius: 8px; padding: 1.5rem; border: 1px solid var(--border); }
  .grid { display: grid; gap: 1rem; }
</style>
</head>
<body>
<div class="container">
  <h1>Enterprise AI Code Review Report</h1>
  <p><strong>Project:</strong> ${rr.project.name} v${rr.project.version} &middot; <strong>Framework:</strong> ${rr.project.framework}</p>
  <p><strong>Generated:</strong> ${new Date().toISOString()} &middot; <strong>Duration:</strong> ${rr.durationMs}ms</p>

  <h2>Scores</h2>
  <div class="scores">
    <div class="score-card"><div class="score-value" style="color:${scoreColor(s.health)}">${s.health}</div><div class="score-label">Health</div></div>
    <div class="score-card"><div class="score-value" style="color:${scoreColor(s.security)}">${s.security}</div><div class="score-label">Security</div></div>
    <div class="score-card"><div class="score-value" style="color:${scoreColor(s.performance)}">${s.performance}</div><div class="score-label">Performance</div></div>
    <div class="score-card"><div class="score-value" style="color:${scoreColor(s.seo)}">${s.seo}</div><div class="score-label">SEO</div></div>
    <div class="score-card"><div class="score-value" style="color:${scoreColor(s.maintainability)}">${s.maintainability}</div><div class="score-label">Maintainability</div></div>
    <div class="score-card"><div class="score-value" style="color:${scoreColor(s.codeQuality)}">${s.codeQuality}</div><div class="score-label">Code Quality</div></div>
    <div class="score-card"><div class="score-value" style="color:${scoreColor(s.architecture)}">${s.architecture}</div><div class="score-label">Architecture</div></div>
    <div class="score-card"><div class="score-value" style="color:${scoreColor(s.overall)}">${s.overall}</div><div class="score-label">Overall</div></div>
  </div>

  <h2>Technical Debt</h2>
  <div class="grid">
    <div>Estimated Fix Time: <strong>${r.technicalDebt.estimatedHours}h</strong></div>
    <div>Complexity: <strong>${r.technicalDebt.complexity}</strong></div>
    <div>Hotspots: ${r.technicalDebt.hotspots.slice(0,5).join(", ") || "None"}</div>
  </div>

  <h2>Findings (${rr.summary.total})</h2>
  <table>
    <thead><tr><th>Severity</th><th>Confidence</th><th>Category</th><th>File:Line</th><th>Message</th><th>Est. Time</th></tr></thead>
    <tbody>
      ${r.priorityList.slice(0, 30).map((p) => `
        <tr>
          <td><span class="badge badge-${p.severity}">${p.severity.toUpperCase()}</span></td>
          <td>${(p.confidence*100).toFixed(0)}%</td>
          <td>${p.category}</td>
          <td>${p.file}:${p.line}</td>
          <td>${sanitizeHtml(p.title)}</td>
          <td>${p.estimatedMinutes}m</td>
        </tr>`).join("")}
    </tbody>
  </table>

  <h2>PR Summary</h2>
  <div class="pr-summary">${r.prSummary.replace(/\n/g, "<br>")}</div>

  <h2>Commit Message</h2>
  <div class="code-block">${r.commitMessage}</div>

  <footer style="margin-top: 3rem; color: var(--dim); text-align: center;">
    Generated by Enterprise AI Code Review System
  </footer>
</div>
</body></html>`;
  }

  private generateArchitectureSection(rr: ReviewResult): string {
    const g = rr.architectureGraph;
    if (!g) return "Architecture graph not available.";
    let result = "Layers:\n";
    for (const layer of g.layers) {
      result += `- ${layer.name} (${layer.files.length} files)\n`;
    }
    result += `\nEntry Points: ${g.entryPoints.join(", ")}\n`;
    const extDeps = g.externalDependencies ?? [];
    result += `\nExternal Dependencies: ${extDeps.slice(0, 15).join(", ")}`;
    return result;
  }
}

function scoreStatus(score: number): string {
  if (score >= 90) return "✅ Excellent";
  if (score >= 75) return "⚠️ Good";
  if (score >= 50) return "⚠️ Needs Attention";
  return "🔴 Critical";
}

function scoreColor(score: number): string {
  if (score >= 90) return "#27ae60";
  if (score >= 75) return "#f39c12";
  if (score >= 50) return "#e67e22";
  return "#e74c3c";
}

function truncate(s: string, n: number): string {
  return s.length > n ? s.slice(0, n - 3) + "..." : s;
}

function verificationSummary(v: import("../types").VerificationResult): string {
  const parts = [
    `lint: ${v.lint.passed ? "✅" : "❌"}`,
    `typecheck: ${v.typecheck.passed ? "✅" : "❌"}`,
    `build: ${v.build.passed ? "✅" : "❌"}`,
    `test: ${v.test.passed ? "✅" : "❌"}`,
  ];
  return parts.join(", ");
}

function sanitizeHtml(s: string): string {
  return s.replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
